nginx:
  image: nginx:1.9.5
  ports:
    - "80:80"
    - "443:443"
  links:
    - php55
    - memcached
  extra_hosts:
    - "local.appsymfony.com:127.0.0.1"
  volumes:
    # - ./app:/usr/share/nginx/html/app
    - ./app:/var/www/html
    - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/logs:/var/log/nginx
memcached:
  image:  memcached
php55:
  image:  rtancman/docker-symfony
  ports:
    - "9000:9000"
  volumes:
    - ./app:/var/www/html
    - phpfpm-foreground:/usr/local/bin/phpfpm-foreground
  entrypoint: /usr/local/bin/phpfpm-foreground

#  nginx
#  docker run -p 80:80 -v `pwd`/app/:/usr/share/nginx/html/app -v `pwd`/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf --link phpapp2:testesymfony nginx

#  using image phpmentors
# docker run --name teste2 -v `pwd`/app:/var/app/web -p 8080:80 -d phpmentors/symfony-app:php55
