nginx:
  image: nginx:1.9.5
  ports:
    - "80:80"
    - "443:443"
  links:
    - php55
    - memcached
  extra_hosts:
    - "local.appsymfony.com:127.0.0.1"
  volumes:
    - ./app:/var/www/html
    - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/logs:/var/log/nginx
memcached:
  image:  memcached
php55:
  image:  rtancman/docker-symfony
  links:
    - memcached
  ports:
    - "9000:9000"
  volumes:
    - ./app:/var/www/html
    - ./phpfpm-foreground:/usr/local/bin/phpfpm-foreground
  entrypoint: /usr/local/bin/phpfpm-foreground